project:
  type: website
  output-dir: docs

website:
  title: "Home"
  site-url: https://zhangqingsen.github.io/Blogs/
  description: "Keeping my notes here."
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://zhangqingsen.github.io/Blogs/
format:
  html:
    theme: spacelab
    css: styles.css












