project:
  type: website
  output-dir: docs

website:
  title: "Blogs"
  site-url: https://zhangqingsen.github.io/Blogs/
  description: "Keeping my notes here."
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - text: "Series: Intro to Python"
        href: posts/intro-to-python/intro_to_python.qmd
      - icon: github
        href: https://zhangqingsen.github.io/Blogs/
format:
  html:
    theme: slate
    css: styles.css
